version: '2.1'
services:
  mysql:
    build: ./config/database
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    healthcheck:
      test: "exit 0"
    restart: always

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always
    command: ["/bin/sh", "-c", "npm run dev:start"]
